
# platform :ios, '6.0'

target 'SingleProgrammersS' do
# Uncomment this line to define a global platform for your projectd
pod  'AFNetworking', '~> 2.6.3'
end

target 'SingleProgrammersSTests' do

end

